### ISSUE TITLE
Plex Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#10]
**Folder Category:** Plex? Maybe Tautulli?
**Animation Suggestion:** Change color of plex icon from plex orange to white and back?
**File:** [plex.zip](https://github.com/ground7/unraid-animated-svgs/files/4714020/plex.zip)

**Comment by ground7** [comment]
Icon seems too specific to me. Might it be better to have a generic media icon instead to be more all encompassing? Also the suggested animation won't work very well with the default color scheme and will limit future recolors.

**Comment by hernandito** [comment]
I already have a multimedia icon... I like Plex idea as there is Plex Server, Ombi, Tautulli... these are Plex exclusive.

Please take a look at the svg I sent you with the Pirate Skull issue.

**Comment by ground7** [comment]
I mainly brought this up because I did not see a multimedia icon in the packages you sent me. Did I miss it? Can you upload it on a new issue? I will attempt to recreate your plex icon with css and an svg version of the plex logo.

**Comment by ground7** [comment]
Will this d0cb069fc6b19a27aebeac82cca3c8f5957730ce work for your recolors? It is the one you originally sent and does not have a second border.

**Comment by hernandito** [comment]
I like it... I also created another one... but it may be more distracting. I will have to study further when doing re-colors.

[plex.zip](https://github.com/ground7/unraid-animated-svgs/files/4723257/plex.zip)

**Comment by ground7** [comment]
That one looks fine to me, but the code is important too, and I don't think we should use ones with embedded pngs. I will close this since you said it will work for your recolors.
