### ISSUE TITLE
Productivity Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#11]
**Folder Category:** Containers that help with productivity
**Animation Suggestion:** ?
**File:** [productivity.zip](https://github.com/ground7/unraid-animated-svgs/files/4714045/productivity.zip)

**Comment by hernandito** [comment]
I created this animation... do you like? Any further ideas?
[productivity.zip](https://github.com/ground7/unraid-animated-svgs/files/4723220/productivity.zip)

**Comment by ground7** [comment]
Hmm... So I think this reminds me of a clock, and I would like to animate it like one.

**Comment by ground7** [comment]
Added in 23c2462b2e4d9cc654e97a56f6df41057e060c27
