### ISSUE TITLE
Torrent Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#14]
**Folder Category:** Torrent related containers
**Animation Suggestion:** white portion slides over to spotlight the logo before exiting
**File:** [torrent.zip](https://github.com/ground7/unraid-animated-svgs/files/4714067/torrent.zip)

**Comment by ground7** [comment]
I don't think this icon represents this category very well since I don't think anyone on unraid is using utorrent

**Comment by hernandito** [comment]
I agree.... I will do some thinking.....

**Comment by hernandito** [comment]
I think I came up with a really good concept. It may be a little tedious to animate, but here it goes.

![Torrent](https://user-images.githubusercontent.com/787317/83642727-36605780-a57d-11ea-9b13-6bffda8fd896.png)

The layout I created consists of 3 layers, background, letters, and then a grid of squares. The grid of square starts as a complete mask over the letters. The each square is individually animated to disappear and reveal the letters underneath. This in essence mimics the concept on a torrent where little bits are randomly downloaded to create the full download. I though of using a "file" icon as the reveal, but it is not obvious enough; thus the word "torrent"

Please advise.

[torrent.zip](https://github.com/ground7/unraid-animated-svgs/files/4723657/torrent.zip)

**Comment by ground7** [comment]
This is a good idea. I'm going to try animating it right now.

**Comment by ground7** [comment]
Added in df86dda6c4591df6c7acb3759d58018fa846cd07

**Comment by hernandito** [comment]
Almost there. Two suggestions. Eliminate the black strokes. And keep “torrent” on for additional time before wiping away. Very nicely done!

**Comment by ground7** [comment]
ok, I will reopen and make those changes

**Comment by ground7** [comment]
Fixes in 267716e5b57db94eb1e6f33caddef2691e1aeb7f
