### ISSUE TITLE
VPN Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#15]
**Folder Category:** Wireguard/openvpn and other related containers
**Animation Suggestion:** ?
**File:** [vpn.zip](https://github.com/ground7/unraid-animated-svgs/files/4714081/vpn.zip)

**Comment by hernandito** [comment]
I was thinking for this icon to have a sliding reflection-glare that swipes diagonally. Like a shield catching a reflection momentarily.

**Comment by ground7** [comment]
Hmm... So I actually am not sure how to do this one. I imagine it would be some kind of rolling gradient, but I can't figure it out with css. Let me know if you manage it with the tools you were using. Otherwise, I think I'll settle for something simpler.

**Comment by ground7** [comment]
Nevermind, I figured it out. You can't do gradient animations with just css (but I don't want to use smil or javascript), so I did static gradients and faded between them. It looks pretty good though it's a bit hefty on code.

**Comment by ground7** [comment]
Added in 4ac00f2a826a95a509a7fbcd9aa660d00371ddda
