### ISSUE TITLE
World Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#16]
**Folder Category:** Remotely accessible stuff
**Animation Suggestion:** ?
**File:** [world.zip](https://github.com/ground7/unraid-animated-svgs/files/4714099/world.zip)

**Comment by sasgoose** [comment]
is it possible to make it spin? I would guess it would be a bit difficult to do?

**Comment by ground7** [comment]
I believe I could achieve a spinning animation by scaling the vertical lines along the x-axis, but they would need to be separate objects. Maybe @hernandito can remake it like this?

**Comment by hernandito** [comment]
[globe.zip](https://github.com/ground7/unraid-animated-svgs/files/4723201/globe.zip)
I created this as a test... do you like it?  I was trying to make the globe act like a basketball thing.

I can attempt to redo the globe with the "verticals" as separate elements. Please advise.

Thanks.

**Comment by ground7** [comment]
The code is very clean on this one and the animation looks nice. I am ok with just adding this one to the repo. However, I am curious if I can make one look like it is spinning using the technique I described. I would like to try if you made one with the separate vertical lines. That is up to you though.

**Comment by hernandito** [comment]
Hi. I have created the world where the verticals are separate elements. Please let me know if this is what you need. I like the idea of spinning too. More straightforward.

Please feel free to increase the thicknesses of the stroke lines. I tried my best to match the earlier version.

![world2](https://user-images.githubusercontent.com/787317/83778568-e3f46900-a658-11ea-902c-873d89f19842.png)

[world2.zip](https://github.com/ground7/unraid-animated-svgs/files/4731170/world2.zip)

**Comment by ground7** [comment]
So, if we assume the sphere has 6 lines around it, then it would need the middle line gone from the initial view, two vertical lines behind the two you have colored, and the side lines need to be broken out too. I can duplicate the two hidden lines in the back easily enough, but would appreciate the sides being broken up from the full image.

**Comment by hernandito** [comment]
Hi.... please let me know if this is not what you need. Every line is a separate entity... but the globe outline needs to be the top layer so it masks the lines beneath. Thanks,
![world3](https://user-images.githubusercontent.com/787317/83926519-0325f000-a758-11ea-8f8a-768ef5f9e082.png)

[world3.zip](https://github.com/ground7/unraid-animated-svgs/files/4738695/world3.zip)

**Comment by ground7** [comment]
This also did not work, but I went ahead and made it myself since it required some special shapes to make it work. Here is the result: d9c817ea58b316c5c9c1e5f979cff02c8c118933
