### ISSUE TITLE
Binoculars Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#2]
**Folder Category:** ?
**Animation Suggestion:** Blink lens?
**File:** [binoculars.zip](https://github.com/ground7/unraid-animated-svgs/files/4713936/binoculars.zip)

**Comment by hernandito** [comment]
I created this icon. I think it works. This could be used as an alternate to the search icon. It gives users a choice.
[binoculars 2.zip](https://github.com/ground7/unraid-animated-svgs/files/4723384/binoculars.2.zip)

**Comment by ground7** [comment]
This is good I will add it.

**Comment by ground7** [comment]
Added in 76b9aa36ebac4c689ae94f63817fa9bd3f28f26f
