### ISSUE TITLE
My Repo

### ISSUE THREAD

**Issue by hernandito** [ground7/unraid-animated-svgs#22]
Hi

I am fairly caught up with conversions. I have also added a few additional icons or alternatives. 

On all of mine, I have taken away the "animate feature only on hover". It was conflicting with the latest version of Docker Folders.

Please feel free to link my repo directly: 
https://github.com/hernandito/unRAID-Docker-Folder-Animated-Icons---Alternate-Colors

We are almost there! Thanks again.

**Comment by ground7** [comment]
I have linked to your repo here: 28bec4913bc2e5dde9e990fdae197d0823ddc2c1
