### ISSUE TITLE
Database Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#4]
**Folder Category:** MariaDB, MongoDB, InfluxDB, etc.
**Animation Suggestion:** ?
**File:** [database.zip](https://github.com/ground7/unraid-animated-svgs/files/4713956/database.zip)

**Comment by hernandito** [comment]
I created this idea... What do you think? Color variations should be straight forward. from a single color to 3 or 4 colors.

[database.zip](https://github.com/ground7/unraid-animated-svgs/files/4723378/database.zip)

**Comment by ground7** [comment]
Yes, I like this. I will add it into the set.

**Comment by ground7** [comment]
Added in 1dedd1d9d7fbf73d79f137b0b6d29f58958a2f2b
