### ISSUE TITLE
Dependencies Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#5]
**Folder Category:** Containers that are required to run other containers
**Animation Suggestion:** ?
**File:** [dependencies.zip](https://github.com/ground7/unraid-animated-svgs/files/4713967/dependencies.zip)

**Comment by hernandito** [comment]
Perhaps this icon should get the second option I outline on the **network** icon. The icon for Network then does the first option.

Network icon:
https://github.com/ground7/unraid-animated-svgs/issues/7

**Comment by ground7** [comment]
If you'd like me to do a line animation, then the svg needs an update as it's not currently using strokes but fill.

**Comment by hernandito** [comment]
Please let me know if this works. Thank you.

![dependencies](https://user-images.githubusercontent.com/787317/83926843-0a013280-a759-11ea-917c-4e15f9f0a75d.png)

[dependencies.zip](https://github.com/ground7/unraid-animated-svgs/files/4738716/dependencies.zip)

**Comment by ground7** [comment]
Hmm, so it looks like line animations are done in css by adjusting width. Since this is curved it doesn't work. I'd like to avoid using smil since it's been almost deprecated several times and is likely to be at some point and then these will stop working. If you figure out a way to do this with css, let me know, but I think I'm going to do something a little different for this one.

**Comment by ground7** [comment]
The end result is a bit different than originally intended, but I think it's still pretty nice. Add in fa9f7bf5abeb8bd88737241ab27b2cc2314c3fc0
