### ISSUE TITLE
Home Automation Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#6]
**Folder Category:** Containers related to home automation
**Animation Suggestion:** Wifi signal fades one element at a time back and forth
**File:** [homeautomation.zip](https://github.com/ground7/unraid-animated-svgs/files/4713981/homeautomation.zip)

**Comment by ground7** [comment]
Added in a6796e6d41dd886828c23b9bfc3a027da1c19369

**Comment by hernandito** [comment]
I think you should add your original Home-Automation icon to the collection as well. The one with the house and the spinning gear. I like it better than my house-wifi concept.
