### ISSUE TITLE
Network Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#7]
**Folder Category:** Containers related to networking
**Animation Suggestion:** ?
**File:**[network.zip](https://github.com/ground7/unraid-animated-svgs/files/4713987/network.zip)

**Comment by hernandito** [comment]
I think it should open with only the top center rectangle visible. Then a mask covering  the lines and bottom boxes slides down revealing them. The bottom portion then fades out and the animation loops again.

As an alternative ( and possibly preferable), Do the icon as a line animation, where the icon draws itself and then the color fills fade in while the strokes fade out. Line animation like:
https://medium.com/bitmatica-lab/svg-line-animation-for-the-uninitiated-5a65d91c6044

**Comment by ground7** [comment]
I decided to animate this one with a packet being transmitted since I ended up doing a fade for dependencies. Let me know what you think. Added in 7a8d68220869685d7b64a7213595b880fd84238e
