### ISSUE TITLE
NZB Icon

### ISSUE THREAD

**Issue by ground7** [ground7/unraid-animated-svgs#8]
**Folder Category:** NZB related containers
**Animation Suggestion:** Pulsate rear arrow transparency
**File:** [nzb.zip](https://github.com/ground7/unraid-animated-svgs/files/4713993/nzb.zip)

**Comment by ground7** [comment]
Since this is essentially the SABnzbd logo, might it be better to have a more generic icon for this category?

**Comment by hernandito** [comment]
I understand. I will create an icon that is generic...

**Comment by hernandito** [comment]
[nzb2.zip](https://github.com/ground7/unraid-animated-svgs/files/4719587/nzb2.zip)
![nzb2](https://user-images.githubusercontent.com/787317/83567719-05861100-a4f0-11ea-877b-f69dbeb36dc5.png)

Hi, The animation should be something like the down arrow slides from the top to the current position. The yellow outline around the nzb letters should be same color as background so arrow sliding gets masked by yellow layer. I hope this eplains it...

Thanks,

**Comment by ground7** [comment]
Added in af30722d0bdfc39d16999c4d2eb354e810323f31
